In [40]:
import numpy as np
import scipy.io as sio
from scipy.sparse import csc_matrix

In [135]:
data_ft = sio.loadmat("ACM-DBLP.mat")
data_ft

{'__header__': b'MATLAB 5.0 MAT-file, Platform: PCWIN64, Created on: Tue Apr  6 10:00:19 2021',
 '__version__': '1.0',
 '__globals__': [],
 'ACM': <9872x9872 sparse matrix of type '<class 'numpy.float64'>'
 	with 79122 stored elements in Compressed Sparse Column format>,
 'ACM_node_feat': array([[61, 42, 16, ..., 14,  1, 22],
        [54, 18, 12, ..., 11,  0, 16],
        [54, 61,  9, ..., 10,  0, 39],
        ...,
        [ 0,  0,  0, ...,  0,  0,  0],
        [ 0,  0,  0, ...,  1,  0,  0],
        [ 0,  0,  0, ...,  0,  0,  1]], dtype=uint8),
 'DBLP': <9916x9916 sparse matrix of type '<class 'numpy.float64'>'
 	with 89616 stored elements in Compressed Sparse Column format>,
 'DBLP_node_feat': array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 4, 1],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 1, 0, 0]], dtype=uint8),
 'H': array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],


In [73]:
data_ft['gnd'].max()

1609

In [23]:
data_ft['alpha']

array([[0.5]])

In [15]:
data_ft['H'].shape

(5120, 5313)

In [16]:
data_ft['n1'], data_ft['n2']

(array([[5313]], dtype=uint16), array([[5120]], dtype=uint16))

In [19]:
data_ft['foursquare']

<5313x5313 sparse matrix of type '<class 'numpy.float64'>'
	with 108466 stored elements in Compressed Sparse Column format>

In [134]:
data_pe = sio.loadmat("cora_org.mat")
data_pe

{'__header__': b'MATLAB 5.0 MAT-file, Platform: MACI64, Created on: Thu Jan 20 20:44:20 2022',
 '__version__': '1.0',
 '__globals__': [],
 'H': array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=uint8),
 'cora1': array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 1, ..., 0, 0, 0],
        [0, 1, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 1],
        [0, 0, 0, ..., 0, 1, 0]], dtype=uint8),
 'cora1_node_feat': array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=uint8),
 'cora2': array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0

In [136]:
data_pe_new = dict()
data_pe_new['cora1'] = csc_matrix(data_pe['cora1'].astype(np.float64))
data_pe_new['cora2'] = csc_matrix(data_pe['cora2'].astype(np.float64))
data_pe_new['cora1_node_feat'] = data_pe['cora1_node_feat'].astype(np.float64)
data_pe_new['cora2_node_feat'] = data_pe['cora2_node_feat'].astype(np.float64)
data_pe_new['H'] = data_pe['H'].astype(np.float64)
data_pe_new['gnd'] = data_pe['gnd'].astype(np.float64)
data_pe_new['n1'] = np.array([[data_pe['cora1'].shape[0]]], dtype=np.float64)
data_pe_new['n2'] = np.array([[data_pe['cora2'].shape[0]]], dtype=np.float64)

data_pe_new['maxiter'] = np.array([[30]], dtype=np.float64)
data_pe_new['tol'] = np.array([[1e-4]], dtype=np.float64)
data_pe_new

{'cora1': <2708x2708 sparse matrix of type '<class 'numpy.float64'>'
 	with 12668 stored elements in Compressed Sparse Column format>,
 'cora2': <2708x2708 sparse matrix of type '<class 'numpy.float64'>'
 	with 9084 stored elements in Compressed Sparse Column format>,
 'cora1_node_feat': array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]),
 'cora2_node_feat': array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 1., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]),
 'H': array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., 

In [137]:
sio.savemat("cora.mat", data_pe_new)

In [61]:
def get_hits(s, gnd, H, topK):
    """
    Calculate Hits@K and MRR
    :param s: alignment score
    :param gnd: ground truth alignment matrix
    :param H: anchor links, shape=(n2, n1)
    :param topK: top-K list
    :return:
        train_p: Hits@K for training pairs
        train_mrr: Mean Reciprocal Rank for training pairs
        test_p: Hits@K for test pairs
        test_mrr: Mean Reciprocal Rank for test pairs
    """

    sortI = torch.argsort(-s, dim=1)

    anchors1, anchors2 = torch.where(H.T == 1)
    anchors = torch.vstack((anchors1, anchors2)).T
    tests = setdiff(gnd, anchors)

    num_train, num_test = anchors.shape[0], tests.shape[0]

    train_ind = []
    train_mrr = 0.0
    for i in range(num_train):
        tempInd = torch.where(sortI[anchors[i, 0]] == anchors[i, 1])[0][0]
        train_ind.append(tempInd)
        train_mrr += 1 / (tempInd + 1)

    train_mrr = train_mrr / num_train

    train_p = []
    for i in range(len(topK)):
        train_p.append(torch.sum(torch.tensor(train_ind) < topK[i]))
    train_p = torch.tensor(train_p).to(torch.float64) / num_train

    test_ind = []
    test_mrr = 0.0
    for i in range(num_test):
        tempInd = torch.where(sortI[tests[i, 0]] == tests[i, 1])[0][0]
        test_ind.append(tempInd)
        test_mrr += 1 / (tempInd + 1)

    test_mrr = test_mrr / num_test

    test_p = []
    for i in range(len(topK)):
        test_p.append(torch.sum(torch.tensor(test_ind) < topK[i]))
    test_p = torch.tensor(test_p).to(torch.float64) / num_test

    return train_p, train_mrr, test_p, test_mrr

def setdiff(a, b):
    """
    Find the difference of two tensors.
    :param a: tensor 1 (n1 x 2)
    :param b: tensor 2 (n2 x 2)
    :return: c: difference of a and b (n3 x 2)
    """
    # Use a structured array to perform row-wise set difference
    a_view = a.view(-1, 1, 2)  # Convert a(tensor) to (n1, 1, 2)
    b_view = b.view(1, -1, 2)  # Convert b(tensor) to (1, n2, 2)

    # Compare each element of a with each element of b
    mask = torch.all(a_view != b_view, dim=2).all(dim=1)

    # Select elements in a that are not in b
    c = a[mask]

    return c

In [130]:
import torch

def test_hit(dataset, use_attr=False):
    data = sio.loadmat(f"{dataset}.mat")
    if dataset == 'ACM-DBLP' and use_attr:
        s = sio.loadmat(f'results/{dataset}-A_S.mat')['S'].T.astype(np.float64)
    else:
        s = sio.loadmat(f'results/{dataset}_S.mat')['S'].T.astype(np.float64)
    s = torch.tensor(s).to(torch.float64)
    gnd = torch.tensor(data['gnd']).to(torch.int64) - 1
    H = torch.tensor(data['H']).to(torch.int64)
    train_p, train_mrr, test_p, test_mrr = get_hits(s, gnd, H, topK=[1, 10, 30, 50, 100])
    return test_p, test_mrr

In [123]:
hits, mrr = test_hit("phone-email")
print(hits)
print(mrr)

tensor([0.0312, 0.2125, 0.4637, 0.6225, 0.8438], dtype=torch.float64)
tensor(0.0988)


In [125]:
hits, mrr = test_hit("foursquare-twitter")
print(hits)
print(mrr)

tensor([0.0404, 0.2362, 0.3590, 0.4071, 0.4553], dtype=torch.float64)
tensor(0.1001)


In [127]:
hits, mrr = test_hit("ACM-DBLP")
print(hits)
print(mrr)

tensor([0.1957, 0.6917, 0.8318, 0.8866, 0.9283], dtype=torch.float64)
tensor(0.3542)


In [133]:
hits, mrr = test_hit("ACM-DBLP", use_attr=True)
print(hits)
print(mrr)

tensor([0.3978, 0.8328, 0.9249, 0.9474, 0.9579], dtype=torch.float64)
tensor(0.5418)


In [139]:
hits, mrr = test_hit("cora")
print(hits)
print(mrr)

tensor([0.7102, 0.8814, 0.9072, 0.9100, 0.9114], dtype=torch.float64)
tensor(0.7734)
